[mypy]
ignore_missing_imports = True
check_untyped_defs = False
no_implicit_optional = True
warn_return_any = False
warn_unused_configs = True

[mypy-tests.*]
ignore_errors = True

[mypy-src.routes.*]
ignore_errors = True
